const CONSTANTS = {
  REGISTRY: 'REGISTRY',
  LOGIN: 'LOGIN',
  ESTABLISH_SESSION: 'ESTABLISH_SESSION',
  SIGN_OFF: 'SIGN_OFF',
  CLEAN_IMAGE_SIGNUP: 'CLEAN_IMAGE_SIGNUP',
  LOAD_IMAGE_SIGNUP: 'LOAD_IMAGE_SIGNUP',
  CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/ds4qyyadp/image/upload',
  CLOIDINARY_PRESET: 'aez4opdo',
  LOAD_IMAGE_PUBLICATION: 'LOAD_IMAGE_PUBLICATION',
  CLEAN_IMAGE_PUBLICATION: 'CLEAN_IMAGE_PUBLICATION',
  UP_PUBLICATION: 'UP_PUBLICATION',
  DOWNLOAD_PUBLICATION: 'DOWNLOAD_PUBLICATION',
  ADD_PUBLICATIONS_STORE: 'ADD_PUBLICATIONS_STORE',
  ADD_AUTHORS_STORE: 'ADD_AUTHORS_STORE',
  SUCCESS_UP_PUBLICATION: 'SUCCESS_UP_PUBLICATION',
  ERROR_UP_PUBLICACION: 'ERROR_UP_PUBLICACION',
  CLEAN_UP_PUBLICACION: 'CLEAN_UP_PUBLICACION',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
};

export default CONSTANTS;
