const CONSTANTES = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLECER_SESION: 'ESTABLECER_SESION',
  CERRAR_SESION: 'CERRAR_SESION',
  LIMPIAR_IMAGEN_SIGNUP: 'LIMPIAR_IMAGEN_SIGNUP',
  CARGAR_IMAGEN_SIGNUP: 'CARGAR_IMAGEN_SIGNUP',
  CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/ds4qyyadp/image/upload',
  CLOIDINARY_PRESET: 'aez4opdo',
};

export default CONSTANTES;
